// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ResizePty(arg1, arg2) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2);
}

export function StartPty(arg1, arg2) {
  return window['go']['main']['App']['StartPty'](arg1, arg2);
}
