// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFolderDialog():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ResizePty(arg1:number,arg2:number):Promise<void>;

export function StartPty(arg1:number,arg2:number):Promise<void>;
