// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClosePty(arg1:string):Promise<void>;

export function HomeDir():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileText(arg1:string,arg2:number):Promise<string>;

export function ResizePty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveExportFile(arg1:string,arg2:string):Promise<string>;

export function StartPty(arg1:string,arg2:number,arg3:number):Promise<void>;
