// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePty(arg1) {
  return window['go']['main']['App']['ClosePty'](arg1);
}

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadFileText(arg1, arg2) {
  return window['go']['main']['App']['ReadFileText'](arg1, arg2);
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2, arg3);
}

export function StartPty(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPty'](arg1, arg2, arg3);
}
